web:
  image: 'softbrix/shatabang-server'
  restart: unless-stopped
  hostname: 'shatabang'
  environment:
   - _BASE_URL=http://localhost:3000/
   - _GOOGLE_AUTH=
   - _GOOGLE_AUTH_ALLOW=
   - _ADMIN_HASH=
   - _SERVER_SALT=
  ports:
    - '3000:3000'
  volumes:
    - './data/cache:/mnt/cache'
    - './data/sorted/:/mnt/sorted'
  links:
    - "redis:redis"
processor:
  image: 'softbrix/shatabang-processor'
  restart: unless-stopped
  volumes:
    - './data/cache:/mnt/cache'
    - './data/sorted/:/mnt/sorted'
  links:
    - "redis:redis"
redis:
  image: redis
webdav:
  image: softbrix/webdav
  ports:
    - "3012:80"
  volumes:
    - ./data/sorted/import:/webdav
  environment:
    - READWRITE=true
    - HTPASSWD=webdav:kK1eUy0t2agv6
