web:
  image: 'softbrix/shatabang-server'
  restart: unless-stopped
  hostname: 'shatabang'
  environment:
   - _BASE_URL=http://localhost:3000/
   - _GOOGLE_AUTH=
   - _GOOGLE_AUTH_ALLOW=
   - _ADMIN_HASH=
   - _SERVER_SALT=
  ports:
    - '3000:3000'
  volumes:
    - './data/cache:/mnt/cache'
    - './data/sorted/:/mnt/sorted'
  links:
    - "redis:redis"
    - "mongo:mongo"
    
processor:
  image: 'softbrix/shatabang-processor'
  restart: unless-stopped
  environment: 
    - _SHARP_FAIL_ON_ERROR=true
    - _IGNORE_DUPLICATES=false
  volumes:
    - './data/cache:/mnt/cache'
    - './data/sorted/:/mnt/sorted'
  links:
    - "redis:redis"
    - "mongo:mongo"

redis:
  image: redis
  volumes:
    - './data/redis:/data'

mongo:
  image: mongo
  volumes:
    - ./data/mongodb:/data/db

webdav:
  image: softbrix/webdav
  ports:
    - "3012:80"
  volumes:
    - ./data/sorted/import:/webdav
  environment:
    - READWRITE=true
    - HTPASSWD=webdav:kK1eUy0t2agv6
