#!/bin/bash
# https://stackoverflow.com/questions/54055666/docker-hub-and-git-submodules
# Docker hub does a recursive clone, then checks the branch out,
# so when a PR adds a submodule (or updates it), it fails.
git submodule update --init