name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        module: ["server", "processor"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: true
    - name: Build the Docker image
      run: ./build_docker.sh ${{ matrix.module }}
